### ISSUE TITLE
Password score from JavaScript ist not the same

### ISSUE THREAD

**Issue by Cyb10101** [bjeavons/zxcvbn-php#33] opened 2018-09-06 14:46 UTC
Hi, the password score of JavaScript is not the same as in PHP.
I guess that should not be like that?

PHP
```
array:6 [
  "password" => "1111"
  "score" => 0
]
array:6 [
  "password" => "Monday"
  "score" => 0
]
array:6 [
  "password" => "Mond!ay"
  "score" => 2
]
```

JavaScript
```
{
  "password": "111",
  "score": 0
}
{
  "password": "Monday",
  "score": 1
}
{
  "password": "Mond!ay",
  "score": 2
}
```

**Comment by mkopinsky** [comment] 2018-09-06 17:26
This is a duplicate of #15 . There's an open PR fixing it at #32. @bjeavons have you had a chance to look at that PR?

**Comment by bjeavons** [comment] 2020-01-27 21:31
master branch now matches JS scoring thanks to @mkopinsky's work!

**Closed by bjeavons** 2020-01-27 21:31 UTC
