### ISSUE TITLE
zxcvbn-php scores lower than zxcvbn.js for dictionary pattern combinations

### ISSUE THREAD

**Issue by vladflip** [bjeavons/zxcvbn-php#35] opened 2019-03-20 17:25 UTC
zxcvbn.js: **4.4.2**
zxcvbn-php: **0.4.0**

### Password: helloworldhello

zxcvbn.js (score: 2)

```
{  
   "password":"helloworldhello",
   "guesses":2132808,
   "guesses_log10":6.328951761078288,
   "sequence":[  
      {  
         "pattern":"dictionary",
         "i":0,
         "j":9,
         "token":"helloworld",
         "matched_word":"helloworld",
         "rank":12788,
         "dictionary_name":"passwords",
         "reversed":false,
         "l33t":false,
         "base_guesses":12788,
         "uppercase_variations":1,
         "l33t_variations":1,
         "guesses":12788,
         "guesses_log10":4.10680262759965
      },
      {  
         "pattern":"dictionary",
         "i":10,
         "j":14,
         "token":"hello",
         "matched_word":"hello",
         "rank":83,
         "dictionary_name":"passwords",
         "reversed":false,
         "l33t":false,
         "base_guesses":83,
         "uppercase_variations":1,
         "l33t_variations":1,
         "guesses":83,
         "guesses_log10":1.919078092376074
      }
   ],
   "calc_time":4,
   "crack_times_seconds":{  
      "online_throttling_100_per_hour":76781088,
      "online_no_throttling_10_per_second":213280.8,
      "offline_slow_hashing_1e4_per_second":213.2808,
      "offline_fast_hashing_1e10_per_second":0.0002132808
   },
   "crack_times_display":{  
      "online_throttling_100_per_hour":"2 years",
      "online_no_throttling_10_per_second":"2 days",
      "offline_slow_hashing_1e4_per_second":"4 minutes",
      "offline_fast_hashing_1e10_per_second":"less than a second"
   },
   "score":2,
   "feedback":{  
      "warning":"",
      "suggestions":[  
         "Add another word or two. Uncommon words are better."
      ]
   }
}
```
zxcvbn-php (score: 0)

```
{  
   "crack_time":41.990400000000086,
   "calc_time":0.020023107528686523,
   "password":"helloworldhello",
   "entropy":19.679700005769252,
   "match_sequence":[  
      {  
         "dictionaryName":"passwords",
         "rank":54,
         "matchedWord":"hello",
         "password":"helloworldhello",
         "begin":0,
         "end":4,
         "token":"hello",
         "pattern":"dictionary",
         "entropy":null,
         "cardinality":null
      },
      {  
         "dictionaryName":"english",
         "rank":288,
         "matchedWord":"world",
         "password":"helloworldhello",
         "begin":5,
         "end":9,
         "token":"world",
         "pattern":"dictionary",
         "entropy":null,
         "cardinality":null
      },
      {  
         "dictionaryName":"passwords",
         "rank":54,
         "matchedWord":"hello",
         "password":"helloworldhello",
         "begin":10,
         "end":14,
         "token":"hello",
         "pattern":"dictionary",
         "entropy":null,
         "cardinality":null
      }
   ],
   "score":0
}
```

### Password: hellodoublestatus

zxcvbn.js (score: 3)

```
{  
   "password":"hellodoublestatus",
   "guesses":399869704,
   "guesses_log10":8.601918501197677,
   "sequence":[  
      {  
         "pattern":"dictionary",
         "i":0,
         "j":4,
         "token":"hello",
         "matched_word":"hello",
         "rank":83,
         "dictionary_name":"passwords",
         "reversed":false,
         "l33t":false,
         "base_guesses":83,
         "uppercase_variations":1,
         "l33t_variations":1,
         "guesses":83,
         "guesses_log10":1.919078092376074
      },
      {  
         "pattern":"dictionary",
         "i":5,
         "j":10,
         "token":"double",
         "matched_word":"double",
         "rank":834,
         "dictionary_name":"english_wikipedia",
         "reversed":false,
         "l33t":false,
         "base_guesses":834,
         "uppercase_variations":1,
         "l33t_variations":1,
         "guesses":834,
         "guesses_log10":2.9211660506377384
      },
      {  
         "pattern":"dictionary",
         "i":11,
         "j":16,
         "token":"status",
         "matched_word":"status",
         "rank":722,
         "dictionary_name":"english_wikipedia",
         "reversed":false,
         "l33t":false,
         "base_guesses":722,
         "uppercase_variations":1,
         "l33t_variations":1,
         "guesses":722,
         "guesses_log10":2.8585371975696385
      }
   ],
   "calc_time":4,
   "crack_times_seconds":{  
      "online_throttling_100_per_hour":14395309344,
      "online_no_throttling_10_per_second":39986970.4,
      "offline_slow_hashing_1e4_per_second":39986.9704,
      "offline_fast_hashing_1e10_per_second":0.0399869704
   },
   "crack_times_display":{  
      "online_throttling_100_per_hour":"centuries",
      "online_no_throttling_10_per_second":"1 year",
      "offline_slow_hashing_1e4_per_second":"11 hours",
      "offline_fast_hashing_1e10_per_second":"less than a second"
   },
   "score":3,
   "feedback":{  
      "warning":"",
      "suggestions":[  

      ]
   }
}
```
zxcvbn-php (score: 1)

```
{  
   "crack_time":8618.50259999999,
   "calc_time":0.020722150802612305,
   "password":"hellodoublestatus",
   "entropy":27.360933897886632,
   "match_sequence":[  
      {  
         "dictionaryName":"passwords",
         "rank":54,
         "matchedWord":"hello",
         "password":"hellodoublestatus",
         "begin":0,
         "end":4,
         "token":"hello",
         "pattern":"dictionary",
         "entropy":null,
         "cardinality":null
      },
      {  
         "dictionaryName":"english",
         "rank":1006,
         "matchedWord":"double",
         "password":"hellodoublestatus",
         "begin":5,
         "end":10,
         "token":"double",
         "pattern":"dictionary",
         "entropy":null,
         "cardinality":null
      },
      {  
         "dictionaryName":"english",
         "rank":3173,
         "matchedWord":"status",
         "password":"hellodoublestatus",
         "begin":11,
         "end":16,
         "token":"status",
         "pattern":"dictionary",
         "entropy":null,
         "cardinality":null
      }
   ],
   "score":1
}
```

**Comment by mkopinsky** [comment] 2019-03-20 20:54
This is a duplicate of #15. If you want a PHP library that directly matches the scores of the Javascript library (for better or for worse), https://github.com/mkopinsky/zxcvbn-php is what you're looking for.

**Closed** 2019-03-21 22:19 UTC
