### ISSUE TITLE
Uncaught Error: [] operator not supported for strings

### ISSUE THREAD

**Issue by fcfidel** [bjeavons/zxcvbn-php#20] opened 2017-01-05 23:54 UTC
**PHP Fatal error:  Uncaught Error: [] operator not supported for strings in 
/vendor/bjeavons/zxcvbn-php/src/Matchers/L33tMatch.php:55**

any ideas how to fix this ?

I'm running **PHP 7.1.0**

I already try : `$result['sub_display'][] = "{$password[$i]} -> $t";`

but I keep getting the same error :(

```
Stack trace:
#0 //vendor/bjeavons/zxcvbn-php/src/Matcher.php(27): ZxcvbnPhp\Matchers\L33tMatch::match('T3H-1337-P@$$', Array)
#1 //vendor/bjeavons/zxcvbn-php/src/Zxcvbn.php(53): ZxcvbnPhp\Matcher->getMatches('T3H-1337-P@$$', Array)
#2 //vendor/phpauth/phpauth/Auth.php(187): ZxcvbnPhp\Zxcvbn->passwordStrength('T3H-1337-P@$$')
#3 /index.php(25): PHPAuth\Auth->register('test@email.com', 'T3H-1337-P@$$', 'T3H-1337-P@$$')
#4 {main}
  thrown in //vendor/bjeavons/zxcvbn-php/src/Matchers/L33tMatch.php on line 55
```

**Comment by sonu27** [comment] 2017-01-06 15:13
+1 I'm getting the same issue with PHP 7.1

See their docs: http://php.net/manual/en/migration71.incompatible.php#migration71.incompatible.empty-string-index-operator

**Comment by sonu27** [comment] 2017-01-06 15:36
FYI: duplicate of #17

**Comment by bjeavons** [comment] 2017-01-06 15:52
Fixed in master and with https://github.com/bjeavons/zxcvbn-php/releases/tag/0.3.0

**Closed by bjeavons** 2017-01-06 15:52 UTC
